name: pizza_app
description: A new Flutter for a Pizza App.
 
 
publish_to: 'none'   
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#-------------------PACKAGES-------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http:
  intl:
  logger:
  lottie: ^2.7.0
  url_launcher:
  connectivity_plus: ^5.0.1
 
  


# Icons
  iconsax: 
  cupertino_icons: ^1.0.2

# State Management
  get: 
  get_storage: ^2.1.1


# Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1


#------------- ./ PACKAGES END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter: 
  uses-material-design: true


  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/
   



  #--------------- LOCAL ASSETS ---------------#
  # fonts:
  